// ── Raw category taxonomy text — fed to GPT VERBATIM ────────────────────────
// This is the exact taxonomy text as provided, with zero transformation.
// Used directly inside the category-classification prompt so there is no
// risk of drift between "what we gave GPT" and "what we validate against."

export const CATEGORY_TAXONOMY_TEXT = `Sports & Athletics: American Football, Archery, Athletics, Australian Football, Badminton, Bandy, Baseball, Basketball, Beach Soccer, Beach Volleyball, Bobsleigh, Bodybuilding, Bowling, Boxing, Brazilian Jiu-Jitsu, Canoeing & Kayaking, Cheerleading, Chess, Climbing, Cricket, Curling, Cycling, Darts, Diving, Equestrian, Esports, Fencing, Field Hockey, Floorball, Football, Futsal, Gaelic Games, Golf, Gymnastics, Handball, Ice Hockey, Ice Skating, Judo, Kabaddi, Karate, Kickboxing, Lacrosse, Marathon & Running, Mixed Martial Arts, Motorsports, Muay Thai, Multi-Sport Events, Netball, Padel, Paralympic Sports, Pickleball, Polo, Powerlifting, Racquetball, Rowing, Rugby League, Rugby Union, Sailing, Sepak Takraw, Skateboarding, Skiing, Snooker & Billiards, Snowboarding, Squash, Strongman, Sumo, Surfing, Swimming, Table Tennis, Taekwondo, Tennis, Triathlon, Volleyball, Water Polo, Weightlifting, Wrestling

Corporate & Finance: Accounting Firms, Asset Management, Banks, Brokerage Firms, Central Banks, Commodity Trading Houses, Conglomerates, Consulting Firms, Credit Rating Agencies, Credit Unions, Cryptocurrency & Blockchain, Development Finance Institutions, Financial Regulators, Fintech, Insurance, Islamic Finance, Law Firms, Leasing & Financing, Microfinance, Payment Networks, Pension Funds, Real Estate, Reinsurance Companies, Sovereign Wealth Funds, Stock Exchanges, Venture Capital & Private Equity, Wealth Management

Government & Politics: Armed Forces, Customs & Immigration, Diplomatic Missions, Electoral Commissions, Environmental Agencies, Fire & Emergency Services, Government Agencies, Intelligence Agencies, Intergovernmental Organizations, International Courts, Judiciary & Courts, Legislative Bodies, Local Governments, National Flags & Emblems, National Governments, Police & Law Enforcement, Political Parties, Postal Services, Public Health Agencies, Regional & State Governments, Tax & Revenue Authorities, Think Tanks

Technology & Media: Advertising & Marketing, Artificial Intelligence & AI Technology, Cloud Computing, Cybersecurity, Drones, Film Studios, Gaming Hardware & Consoles, Gaming Platforms & Publishers, Hardware & Electronics, Internet & Web Services, Internet Service Providers, Music Labels, News & Media Publishers, Photography & Imaging, Podcasts & Podcast Networks, Publishing Houses, Radio, Robotics, Semiconductors, Smartphones, Social Media, Software, Streaming Services, Telecommunications, Television Networks, Wearable Technology, Web3 & Blockchain

Automotive & Transport: Aircraft Manufacturers, Airlines, Airports, Auto Parts & Components, Bicycles, Buses & Coaches, Car Manufacturers, Car Rental & Leasing, Cruise Lines, Electric Vehicles, Logistics & Delivery, Marine & Boats, Motorcycles, Ports & Maritime, Public Transit, Rail Manufacturers, Railways, Ride-Hailing & Mobility, Shipping & Cargo, Space & Aerospace, Tires, Trucks & Commercial Vehicles

Food & Beverages: Baby Food, Bakery & Confectionery, Beer, Bottled Water, Cafes & Coffee Shops, Cereal & Breakfast Foods, Chocolate & Candy, Coffee, Condiments & Sauces, Cooking Oil & Ghee, Dairy Products, Energy Drinks, Fast Food, Food Delivery, Frozen Foods, Grocery & Supermarkets, Health & Organic Foods, Ice Cream, Instant Noodles, Juices, Meat & Poultry, Pizza Chains, Plant-Based & Alternative Foods, Restaurants, Rice & Grains, Seafood, Snacks, Soft Drinks, Spirits & Liquor, Sugar & Sweeteners, Tea, Wine

Industry, Energy & Construction: Agricultural Machinery, Agriculture & Farming, Architecture & Design, Biofuels, Building Materials, Carbon Capture & Climate Tech, Cement, Chemicals, Coal, Construction Companies, Critical Minerals & Rare Earths, Defense & Aerospace, Electric Utilities, Electrical Equipment, Elevators & Escalators, Energy Storage & Batteries, Environmental Services, Fertilizers & Agrochemicals, Fisheries & Aquaculture, Forestry & Timber, Geothermal Energy, Glass Manufacturing, HVAC & Building Systems, Heavy Equipment, Hydrogen Energy, Hydropower, Industrial Conglomerates, Industrial Gases, Industrial Machinery, Infrastructure & Engineering, Mining & Metals, Nuclear Energy, Oil & Gas, Packaging, Paper & Pulp, Petrochemicals, Plastics & Rubber, Power Grid, Power Tools & Hardware Brands, Shipbuilding, Solar Energy, Steel, Textile Manufacturing, Waste Management & Recycling, Water Utilities, Wind Energy

Fashion & Retail: Apparel & Clothing, Baby & Maternity Products, Beauty & Cosmetics, Bookstores, Children's Apparel, Convenience Stores, Department Stores, Discount Stores, Duty-Free & Travel Retail, E-commerce, Electronics Retail, Eyewear, Fast Fashion, Footwear, Handbags & Accessories, Home & Furniture Retail, Home Improvement & Hardware, Jewelry & Watches, Lingerie & Innerwear, Luxury Fashion, Outdoor & Camping Gear, Perfume & Fragrance, Pet Supplies, Second-Hand & Thrift, Sporting Goods Retail, Sportswear, Stationery & Office Supplies, Toys

Healthcare & Pharma: Biotechnology, Blood Banks & Donation, Clinical Research Organizations, Clinics, Cosmetic & Plastic Surgery, Dental Care, Diagnostics & Labs, Emergency Medical Services, Fertility Clinics, Generic Drugs, Home Healthcare, Hospice & Palliative Care, Hospitals, Medical & Health Associations, Medical Devices, Medical Tourism, Mental Health Services, Nursing & Elder Care, Nutraceuticals & Supplements, Pharmaceutical Companies, Pharmacy Chains, Rehabilitation Centers, Surgical Centers, Telemedicine & Digital Health, Veterinary Care, Vision Care

Education & Science: Academic & Scientific Publishing, Business Schools & MBA Programs, Coding Bootcamps, Education Authorities, Educational Foundations, International Schools, Language Schools, Libraries, Observatories & Astronomy, Online Learning & EdTech, Preschools & Early Childhood Education, Research Institutes, Schools (K-12), Science Academies & Societies, Science Centers & Museums, Special Education, Standards Organizations, Test Prep & Certification, Universities & Colleges, Vocational & Technical Training

Non-Profit & Culture: Animal Welfare Organizations, Art Museums & Galleries, Chambers of Commerce, Charities & Foundations, Child Welfare & Protection Organizations, Community & Social Services, Cultural Centers & Institutes, Cultural Festivals & Events, Cultural Heritage & Preservation, Disability Support, Environmental NGOs, Ethnic & Cultural Associations, Historical Societies, Human Rights Organizations, Humanitarian & Disaster Relief, International Aid, LGBTQ+ Organizations, Labor Unions, Religious Organizations, Social & Fraternal Clubs, Trade Associations, Veterans Organizations, Volunteer Organizations, Women's Rights Organizations, Youth Organizations

Entertainment & Lifestyle: Cannabis & CBD, Casinos & Gambling, Cinemas & Movie Theater Chains, Circus & Live Shows, Dating & Matchmaking, Escape Rooms, Fitness & Gyms, Hobbies & Crafts, Karaoke Entertainment, Live Events & Concerts, Lottery, Nightlife & Bars, Pet Care & Grooming, Photography Studios, Talent & Modeling Agencies, Tattoo & Piercing Studios, Theatre & Performing Arts, Theme Parks & Attractions, Wedding & Event Planning, Wellness & Spa, Yoga & Meditation, Zoos & Aquariums

Travel & Hospitality: Adventure & Eco Tourism, Bed & Breakfasts, Budget & Economy Hotels, Camping & Glamping, Corporate Travel, Hostels, Hotels, Luxury Hotels, Online Travel Booking Platforms, Resorts, Serviced Apartments, Timeshare & Vacation Clubs, Tour Operators, Tourism Boards, Travel Agencies, Travel Technology & Booking Systems (GDS), Vacation Rentals`;