// ── Static category taxonomy (hardcoded) ────────────────────────────────────
// Used in place of website.categories from the DB, for now.
// Same shape as extractCategoryEntries() output: { name, subname, brand, country, etype, synonyms }

export const STATIC_CATEGORIES = [
  { name: "Sports & Athletics", subname: "American Football", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Archery", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Athletics", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Australian Football", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Badminton", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Bandy", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Baseball", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Basketball", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Beach Soccer", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Beach Volleyball", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Bobsleigh", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Bodybuilding", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Bowling", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Boxing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Brazilian Jiu-Jitsu", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Canoeing & Kayaking", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Cheerleading", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Chess", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Climbing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Cricket", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Curling", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Cycling", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Darts", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Diving", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Equestrian", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Esports", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Fencing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Field Hockey", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Floorball", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Football", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Futsal", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Gaelic Games", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Golf", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Gymnastics", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Handball", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Ice Hockey", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Ice Skating", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Judo", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Kabaddi", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Karate", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Kickboxing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Lacrosse", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Marathon & Running", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Mixed Martial Arts", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Motorsports", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Muay Thai", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Multi-Sport Events", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Netball", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Padel", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Paralympic Sports", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Pickleball", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Polo", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Powerlifting", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Racquetball", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Rowing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Rugby League", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Rugby Union", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Sailing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Sepak Takraw", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Skateboarding", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Skiing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Snooker & Billiards", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Snowboarding", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Squash", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Strongman", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Sumo", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Surfing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Swimming", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Table Tennis", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Taekwondo", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Tennis", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Triathlon", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Volleyball", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Water Polo", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Weightlifting", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Sports & Athletics", subname: "Wrestling", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Accounting Firms", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Asset Management", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Banks", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Brokerage Firms", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Central Banks", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Commodity Trading Houses", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Conglomerates", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Consulting Firms", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Credit Rating Agencies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Credit Unions", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Cryptocurrency & Blockchain", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Development Finance Institutions", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Financial Regulators", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Fintech", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Insurance", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Islamic Finance", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Law Firms", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Leasing & Financing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Microfinance", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Payment Networks", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Pension Funds", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Real Estate", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Reinsurance Companies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Sovereign Wealth Funds", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Stock Exchanges", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Venture Capital & Private Equity", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Corporate & Finance", subname: "Wealth Management", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Armed Forces", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Customs & Immigration", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Diplomatic Missions", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Electoral Commissions", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Environmental Agencies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Fire & Emergency Services", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Government Agencies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Intelligence Agencies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Intergovernmental Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "International Courts", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Judiciary & Courts", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Legislative Bodies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Local Governments", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "National Flags & Emblems", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "National Governments", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Police & Law Enforcement", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Political Parties", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Postal Services", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Public Health Agencies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Regional & State Governments", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Tax & Revenue Authorities", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Government & Politics", subname: "Think Tanks", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Advertising & Marketing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Artificial Intelligence & AI Technology", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Cloud Computing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Cybersecurity", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Drones", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Film Studios", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Gaming Hardware & Consoles", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Gaming Platforms & Publishers", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Hardware & Electronics", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Internet & Web Services", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Internet Service Providers", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Music Labels", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "News & Media Publishers", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Photography & Imaging", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Podcasts & Podcast Networks", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Publishing Houses", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Radio", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Robotics", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Semiconductors", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Smartphones", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Social Media", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Software", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Streaming Services", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Telecommunications", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Television Networks", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Wearable Technology", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Technology & Media", subname: "Web3 & Blockchain", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Aircraft Manufacturers", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Airlines", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Airports", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Auto Parts & Components", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Bicycles", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Buses & Coaches", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Car Manufacturers", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Car Rental & Leasing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Cruise Lines", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Electric Vehicles", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Logistics & Delivery", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Marine & Boats", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Motorcycles", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Ports & Maritime", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Public Transit", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Rail Manufacturers", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Railways", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Ride-Hailing & Mobility", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Shipping & Cargo", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Space & Aerospace", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Tires", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Automotive & Transport", subname: "Trucks & Commercial Vehicles", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Baby Food", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Bakery & Confectionery", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Beer", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Bottled Water", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Cafes & Coffee Shops", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Cereal & Breakfast Foods", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Chocolate & Candy", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Coffee", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Condiments & Sauces", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Cooking Oil & Ghee", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Dairy Products", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Energy Drinks", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Fast Food", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Food Delivery", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Frozen Foods", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Grocery & Supermarkets", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Health & Organic Foods", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Ice Cream", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Instant Noodles", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Juices", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Meat & Poultry", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Pizza Chains", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Plant-Based & Alternative Foods", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Restaurants", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Rice & Grains", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Seafood", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Snacks", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Soft Drinks", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Spirits & Liquor", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Sugar & Sweeteners", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Tea", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Food & Beverages", subname: "Wine", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Agricultural Machinery", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Agriculture & Farming", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Architecture & Design", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Biofuels", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Building Materials", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Carbon Capture & Climate Tech", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Cement", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Chemicals", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Coal", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Construction Companies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Critical Minerals & Rare Earths", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Defense & Aerospace", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Electric Utilities", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Electrical Equipment", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Elevators & Escalators", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Energy Storage & Batteries", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Environmental Services", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Fertilizers & Agrochemicals", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Fisheries & Aquaculture", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Forestry & Timber", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Geothermal Energy", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Glass Manufacturing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "HVAC & Building Systems", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Heavy Equipment", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Hydrogen Energy", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Hydropower", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Industrial Conglomerates", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Industrial Gases", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Industrial Machinery", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Infrastructure & Engineering", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Mining & Metals", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Nuclear Energy", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Oil & Gas", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Packaging", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Paper & Pulp", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Petrochemicals", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Plastics & Rubber", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Power Grid", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Power Tools & Hardware Brands", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Shipbuilding", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Solar Energy", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Steel", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Textile Manufacturing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Waste Management & Recycling", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Water Utilities", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Industry, Energy & Construction", subname: "Wind Energy", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Apparel & Clothing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Baby & Maternity Products", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Beauty & Cosmetics", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Bookstores", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Children's Apparel", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Convenience Stores", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Department Stores", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Discount Stores", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Duty-Free & Travel Retail", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "E-commerce", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Electronics Retail", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Eyewear", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Fast Fashion", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Footwear", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Handbags & Accessories", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Home & Furniture Retail", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Home Improvement & Hardware", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Jewelry & Watches", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Lingerie & Innerwear", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Luxury Fashion", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Outdoor & Camping Gear", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Perfume & Fragrance", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Pet Supplies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Second-Hand & Thrift", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Sporting Goods Retail", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Sportswear", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Stationery & Office Supplies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Fashion & Retail", subname: "Toys", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Biotechnology", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Blood Banks & Donation", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Clinical Research Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Clinics", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Cosmetic & Plastic Surgery", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Dental Care", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Diagnostics & Labs", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Emergency Medical Services", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Fertility Clinics", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Generic Drugs", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Home Healthcare", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Hospice & Palliative Care", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Hospitals", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Medical & Health Associations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Medical Devices", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Medical Tourism", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Mental Health Services", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Nursing & Elder Care", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Nutraceuticals & Supplements", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Pharmaceutical Companies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Pharmacy Chains", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Rehabilitation Centers", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Surgical Centers", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Telemedicine & Digital Health", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Veterinary Care", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Healthcare & Pharma", subname: "Vision Care", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Academic & Scientific Publishing", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Business Schools & MBA Programs", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Coding Bootcamps", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Education Authorities", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Educational Foundations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "International Schools", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Language Schools", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Libraries", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Observatories & Astronomy", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Online Learning & EdTech", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Preschools & Early Childhood Education", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Research Institutes", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Schools (K-12)", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Science Academies & Societies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Science Centers & Museums", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Special Education", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Standards Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Test Prep & Certification", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Universities & Colleges", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Education & Science", subname: "Vocational & Technical Training", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Animal Welfare Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Art Museums & Galleries", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Chambers of Commerce", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Charities & Foundations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Child Welfare & Protection Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Community & Social Services", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Cultural Centers & Institutes", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Cultural Festivals & Events", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Cultural Heritage & Preservation", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Disability Support", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Environmental NGOs", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Ethnic & Cultural Associations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Historical Societies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Human Rights Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Humanitarian & Disaster Relief", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "International Aid", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "LGBTQ+ Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Labor Unions", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Religious Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Social & Fraternal Clubs", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Trade Associations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Veterans Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Volunteer Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Women's Rights Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Non-Profit & Culture", subname: "Youth Organizations", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Cannabis & CBD", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Casinos & Gambling", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Cinemas & Movie Theater Chains", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Circus & Live Shows", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Dating & Matchmaking", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Escape Rooms", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Fitness & Gyms", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Hobbies & Crafts", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Karaoke Entertainment", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Live Events & Concerts", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Lottery", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Nightlife & Bars", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Pet Care & Grooming", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Photography Studios", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Talent & Modeling Agencies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Tattoo & Piercing Studios", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Theatre & Performing Arts", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Theme Parks & Attractions", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Wedding & Event Planning", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Wellness & Spa", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Yoga & Meditation", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Entertainment & Lifestyle", subname: "Zoos & Aquariums", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Adventure & Eco Tourism", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Bed & Breakfasts", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Budget & Economy Hotels", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Camping & Glamping", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Corporate Travel", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Hostels", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Hotels", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Luxury Hotels", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Online Travel Booking Platforms", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Resorts", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Serviced Apartments", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Timeshare & Vacation Clubs", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Tour Operators", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Tourism Boards", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Travel Agencies", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Travel Technology & Booking Systems (GDS)", brand: "", country: "", etype: "", synonyms: [] },
  { name: "Travel & Hospitality", subname: "Vacation Rentals", brand: "", country: "", etype: "", synonyms: [] },
];